CREATE TABLE TMP_BOARD(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    TITLE VARCHAR(100),
    CONTENT TEXT,
    WRITE_DATE DATETIME DEFAULT NOW(),

    FOREIGN KEY (USER_ID)
    REFERENCES USER(ID) ON UPDATE CASCADE
)